{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.databinding",
    "module": "databinding-adapters",
    "version": "7.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-7.4.1.aar",
          "url": "databinding-adapters-7.4.1.aar",
          "size": 81465,
          "sha512": "a1ce0b9b2b726d5a7024472659a52795425c8622ab0f8ce3001d72f1180b41ca899ca161dfbc026904ab999129e4c9745170e600bf6af25e63669f5ce385db81",
          "sha256": "46e70be5ae25007cb46ffd967a024dad8ae006970ec45ff984bd71927ef97401",
          "sha1": "efc728474d22179288a7b384c8606c3ab21a739c",
          "md5": "c44add8ff30cee3cb4a67a4678de8dd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "7.4.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "7.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "databinding-adapters-7.4.1.aar",
          "url": "databinding-adapters-7.4.1.aar",
          "size": 81465,
          "sha512": "a1ce0b9b2b726d5a7024472659a52795425c8622ab0f8ce3001d72f1180b41ca899ca161dfbc026904ab999129e4c9745170e600bf6af25e63669f5ce385db81",
          "sha256": "46e70be5ae25007cb46ffd967a024dad8ae006970ec45ff984bd71927ef97401",
          "sha1": "efc728474d22179288a7b384c8606c3ab21a739c",
          "md5": "c44add8ff30cee3cb4a67a4678de8dd7"
        }
      ]
    }
  ]
}
